language: node_js
node_js:
  - node
deploy:
  provider: s3
  access_key_id: AKIAXFMUCTMRVBZZTX6Y
  secret_access_key:
    secure: p7+geDq3HiW/5TLdhpdFao0JsfMjf3gI66wX0rTQGsjl3zBKLCrMOk8NM2pkz+KVQYFyCdKFhpAq4V5BV0YrqPkNZoTeWgJyW6GXZYlHIzpdq4k5kw29nbLzDVRmeUekdF4gGybKWHYmOtdld6QGWPnvscPSCRndyeUJdwqKsxiqO4WpVO8oWpSoaMPPhL9AKeawrObjrC6ia6Txjc8WERh35fHeXVCBQrlODvlwpqsOMQDZOeIsDhf9UK+EQmXpE/myNYhvQfHI9q1hxBUENIW66mHhASM+llxXQxFLnSOBnjhPOmFvpgLm75hT7zb4EDTq7tYTXwPR8vJc7RLqRuX/8YWR7j/psAKqDbM0tW/gPACi3nR935Q4GNExJFNpFhL2DzgKV+kKRiwxJob6fW9qsiKPCZMYs6wtKp7zyMZ6pulYQkqnX4BLYZ5cDjns2+c6ih9X+D0M8Sgv+4J6ExXXwjxdokAtZ3kyf5hQHG4jA/oH1d2aGbmBsfqEh7ZX9uv51lQZ1Vc2GEKnMF8jVtPu666JkjelHlyMp4/SKBr0j92erGmAcOajC8Sg84uGw48J++8kOX4zNKVIN0xW98A/ibCYJ/mY5Qbu/TGC6nhjoRHBpSKWERKDgAw92njbCGIxnMbgdKXusc2dETNCN5GmLi7XM6OyjnXy9u6nJ5k=
  bucket: bwjobsforgraduates
